name: app_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  shadcn_ui: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: noto-serif-khmer
      fonts:
        - asset: assets/fonts/noto_serif_khmer.ttf
          weight: 800
        - asset: assets/fonts/noto_serif_khmer.ttf
          weight: 700
        - asset: assets/fonts/noto_serif_khmer.ttf
          weight: 600
        - asset: assets/fonts/noto_serif_khmer.ttf
          weight: 500
        - asset: assets/fonts/noto_serif_khmer.ttf
          weight: 400
        - asset: assets/fonts/noto_serif_khmer.ttf
          weight: 300
        - asset: assets/fonts/noto_serif_khmer.ttf
          weight: 200
  uses-material-design: true
  generate: true
  module:
    androidPackage: com.example.app_ui
    iosBundleIdentifier: com.example.appUi

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true

