// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkSZgCiIFvVPR4bnBLgkJYqtuQ69MSsXg',
    appId: '1:1072879903076:web:7459e780c62c33cebf1a71',
    messagingSenderId: '1072879903076',
    projectId: 'eyes-diseases-detector',
    authDomain: 'eyes-diseases-detector.firebaseapp.com',
    storageBucket: 'eyes-diseases-detector.appspot.com',
    measurementId: 'G-B6RHHWS80F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYjSdNrq0PVmv4RMLc2atycqNAYhcnLVg',
    appId: '1:1072879903076:android:ae2810265d963b44bf1a71',
    messagingSenderId: '1072879903076',
    projectId: 'eyes-diseases-detector',
    storageBucket: 'eyes-diseases-detector.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7PElE6IReF4-O0ZX-yVh--PSsDzJkLA',
    appId: '1:1072879903076:ios:dd270c13fe573274bf1a71',
    messagingSenderId: '1072879903076',
    projectId: 'eyes-diseases-detector',
    storageBucket: 'eyes-diseases-detector.appspot.com',
    iosClientId: '1072879903076-8733qrv7hf0riur6ui5g2apknd3jqu84.apps.googleusercontent.com',
    iosBundleId: 'com.example.diseaseDetectorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw7PElE6IReF4-O0ZX-yVh--PSsDzJkLA',
    appId: '1:1072879903076:ios:dd270c13fe573274bf1a71',
    messagingSenderId: '1072879903076',
    projectId: 'eyes-diseases-detector',
    storageBucket: 'eyes-diseases-detector.appspot.com',
    iosClientId: '1072879903076-8733qrv7hf0riur6ui5g2apknd3jqu84.apps.googleusercontent.com',
    iosBundleId: 'com.example.diseaseDetectorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkSZgCiIFvVPR4bnBLgkJYqtuQ69MSsXg',
    appId: '1:1072879903076:web:d78219360c96e83cbf1a71',
    messagingSenderId: '1072879903076',
    projectId: 'eyes-diseases-detector',
    authDomain: 'eyes-diseases-detector.firebaseapp.com',
    storageBucket: 'eyes-diseases-detector.appspot.com',
    measurementId: 'G-J92RJ583P3',
  );
}
