import 'package:flutter/material.dart';

class M3Theme {
  M3Theme._();

  static ColorScheme light() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff004daa),
      surfaceTint: Color(0xff005ac4),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff2771e3),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff4f5e82),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff8e9dc5),
      onSecondaryContainer: Color(0xff000e2d),
      tertiary: Color(0xff005097),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff2c75ca),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfffaf9ff),
      onSurface: Color(0xff191b22),
      onSurfaceVariant: Color(0xff424753),
      outline: Color(0xff727785),
      outlineVariant: Color(0xffc2c6d6),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff2e3038),
      inversePrimary: Color(0xffaec6ff),
      primaryFixed: Color(0xffd8e2ff),
      onPrimaryFixed: Color(0xff001a42),
      primaryFixedDim: Color(0xffaec6ff),
      onPrimaryFixedVariant: Color(0xff004396),
      secondaryFixed: Color(0xffd9e2ff),
      onSecondaryFixed: Color(0xff091a3b),
      secondaryFixedDim: Color(0xffb7c6f0),
      onSecondaryFixedVariant: Color(0xff374669),
      tertiaryFixed: Color(0xffd5e3ff),
      onTertiaryFixed: Color(0xff001c3b),
      tertiaryFixedDim: Color(0xffa6c8ff),
      onTertiaryFixedVariant: Color(0xff004787),
      surfaceDim: Color(0xffd8d9e3),
      surfaceBright: Color(0xfffaf9ff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff2f3fd),
      surfaceContainer: Color(0xffecedf7),
      surfaceContainerHigh: Color(0xffe7e7f2),
      surfaceContainerHighest: Color(0xffe1e2ec),
    );
  }

  static ColorScheme dark() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffaec6ff),
      surfaceTint: Color(0xffaec6ff),
      onPrimary: Color(0xff002e6b),
      primaryContainer: Color(0xff0058c1),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xffb7c6f0),
      onSecondary: Color(0xff203051),
      secondaryContainer: Color(0xff65749a),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xffa6c8ff),
      onTertiary: Color(0xff003060),
      tertiaryContainer: Color(0xff226ec3),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff11131a),
      onSurface: Color(0xffe1e2ec),
      onSurfaceVariant: Color(0xffc2c6d6),
      outline: Color(0xff8c909f),
      outlineVariant: Color(0xff424753),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe1e2ec),
      inversePrimary: Color(0xff005ac4),
      primaryFixed: Color(0xffd8e2ff),
      onPrimaryFixed: Color(0xff001a42),
      primaryFixedDim: Color(0xffaec6ff),
      onPrimaryFixedVariant: Color(0xff004396),
      secondaryFixed: Color(0xffd9e2ff),
      onSecondaryFixed: Color(0xff091a3b),
      secondaryFixedDim: Color(0xffb7c6f0),
      onSecondaryFixedVariant: Color(0xff374669),
      tertiaryFixed: Color(0xffd5e3ff),
      onTertiaryFixed: Color(0xff001c3b),
      tertiaryFixedDim: Color(0xffa6c8ff),
      onTertiaryFixedVariant: Color(0xff004787),
      surfaceDim: Color(0xff11131a),
      surfaceBright: Color(0xff363941),
      surfaceContainerLowest: Color(0xff0b0e15),
      surfaceContainerLow: Color(0xff191b22),
      surfaceContainer: Color(0xff1d1f27),
      surfaceContainerHigh: Color(0xff272a31),
      surfaceContainerHighest: Color(0xff32353c),
    );
  }
}
